DEVICE_CONFIG_TIMER_FD		400
DEVICE_CONFIG_UART_BASENAME	__ev3rt_uart
DEVICE_CONFIG_BT_BASENAME	__ev3rt_bt
DEVICE_CONFIG_VIRTFS_TOP	__ev3rtfs
DEBUG_FUNC_ENABLE_FT		1
DEBUG_FUNC_ENABLE_BT		1
DEBUG_FUNC_ENABLE_PROF		1
DEBUG_FUNC_ENABLE_WATCH		1
DEBUG_FUNC_ENABLE_SKIP_CLOCK    1
DEBUG_FUNC_ENABLE_SYNC_TIME	0
DEBUG_FUNC_ENABLE_EV3COM	1
DEBUG_FUNC_EV3COM_SIMSYNC_TYPE	MMAP
DEBUG_FUNC_EV3COM_MMAP_TX      	0x40000000
DEBUG_FUNC_EV3COM_MMAP_RX      	0x40010000

